-- Casa Film — dashboard upgrade (drag-to-reorder, folders, storage tracking)
--
-- ⚠️ This file is NOT applied automatically. Run it once, yourself, in the
-- Supabase SQL Editor (or via `supabase db push` if you use the CLI) before
-- the new dashboard features (folders, gallery reordering, storage badges)
-- will work. Until this runs, those features will silently no-op — the app
-- checks for errors and won't crash, but drag-reorder / folder assignment /
-- storage numbers won't persist.
--
-- Safe to re-run: every statement is guarded with IF NOT EXISTS.

-- 1) Gallery drag-to-reorder ------------------------------------------------
alter table galleries add column if not exists "order" integer;

-- Backfill existing rows so current (created_at-desc) order is preserved
-- the first time the dashboard loads after this migration.
update galleries g
set "order" = sub.rn
from (
  select id, row_number() over (partition by user_id order by created_at desc) as rn
  from galleries
) sub
where g.id = sub.id and g."order" is null;

-- 2) Folders / categories ----------------------------------------------------
create table if not exists folders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

alter table galleries add column if not exists folder_id bigint references folders(id) on delete set null;

alter table folders enable row level security;

drop policy if exists "Users can view their own folders" on folders;
create policy "Users can view their own folders"
  on folders for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own folders" on folders;
create policy "Users can insert their own folders"
  on folders for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own folders" on folders;
create policy "Users can update their own folders"
  on folders for update
  using (auth.uid() = user_id);

drop policy if exists "Users can delete their own folders" on folders;
create policy "Users can delete their own folders"
  on folders for delete
  using (auth.uid() = user_id);

-- Note: if your `galleries`/`videos` tables don't currently use RLS (e.g.
-- access is controlled entirely client-side), you may want to relax or
-- remove the folders policies above to match — adjust to your existing
-- security model.

-- 3) Storage tracking (cached from Cloudflare Stream) ------------------------
-- Populated lazily by the dashboard the first time it displays a video
-- whose size isn't cached yet (see GET /api/stream/[uid]).
alter table videos add column if not exists size_bytes bigint;
alter table galleries add column if not exists video_size_bytes bigint;
